### PR TITLE
Slash commands example: parse options into a map

### PR DESCRIPTION
**Pull request by switchupcb**
https://github.com/bwmarrin/discordgo/issues/1126 [Method 3](https://github.com/bwmarrin/discordgo/issues/1126#issuecomment-1062543250)

The resulting example output:
image

image

### CODE REVIEW

**Comment by switchupcb** [comment]
If options can be recursive, we can implement that to the existing loop while unmarshalling. Otherwise, this should be good to go!

**Comment by switchupcb** [comment]
If the subcommand example is correct, there can be parsed recursive options. However, they can't have the same name as other options. I will implement a recursive parse and example tomorrow.

**Comment by switchupcb** [comment]
image
image
image
image

**Review by FedorLap2006 — CHANGES_REQUESTED** [review]
As I said in the original issue, DiscordGo is 1:1 mapping of Discord API. I don't think that adding an extra option, which would be just a reflection of the original, would be a good idea.
That said, I think it would fair to still showcase parsing options into a map in the example.

Additionally, note my comments for some other stuff.

**Review by FedorLap2006 — APPROVED** [review]

**Pull request merged**
