### PR TITLE
GuildBan method and UnknownBan error code addition

### PR DESCRIPTION
**Pull request by FedorLap2006**
I added UnknownBan code to error codes in structs.go and also I made GuildBan method, so we can now get user's ban in a guild.

### CODE REVIEW

**Comment by CarsonHoffman** [comment]
I only see the addition of `ErrCodeUnknownBan`; it looks like you may have forgotten to add the other changes. 🙂

**Comment by FedorLap2006** [comment]
> I only see the addition of `ErrCodeUnknownBan`; it looks like you may have forgotten to add the other changes.

Oh... right. Wait a sec. I will upload them

**Comment by FedorLap2006** [comment]
Everything is ok... but note: I've done commit amend, so if something broke, please mention me :slightly_smiling_face:

**Comment by FedorLap2006** [comment]
Btw, why is the check still tries to run itself?

**Comment by CarsonHoffman** [comment]
Thank you for the contribution (and following up with the CI)!

**Pull request merged**
