### PR TITLE
Context menus

### PR DESCRIPTION
**Pull request by FedorLap2006**
Lo and behold, context menus are coming.

### CODE REVIEW

**Comment by FedorLap2006** [comment]
And sorry again for the broken PR, the GitHub is kinda confused about the commits since I didn't merge them properly.

**Comment by Nv7-GitHub** [comment]
What do these look like?

**Comment by FedorLap2006** [comment]
I'm unsure if I can show the screenshots. But believe me. Amazing.

**Comment by FedorLap2006** [comment]
Due to https://github.com/discord/discord-api-docs/pull/3614 I'm undrafting this. Enjoy!

**Pull request merged**
