### PR TITLE
Application commands: Permissions v2

### PR DESCRIPTION
**Pull request by FedorLap2006**
Implements permissions v2 API for application commands

ref: https://github.com/discord/discord-api-docs/pull/4830

### CODE REVIEW

**Comment by QPixel** [comment]
:eyes:

**Comment by Nv7-GitHub** [comment]
Need these

**Comment by FedorLap2006** [comment]
> Need these

They are still unreleased. Sorry.

**Comment by FedorLap2006** [comment]
Slash command permissions were finally released. The following [PR](https://github.com/discord/discord-api-docs/pull/4830) contains the new documentation for them, and should be merged shortly.

**Pull request merged**
