### PR TITLE
Rich Presence

### PR DESCRIPTION
**Pull request by SilverCory**
Not perfect, from what I can see there's still fields missing
- partySize
- partyMax
- partyId
- matchSecret
- joinSecret
- spectateSecret
- instance

Whilst I could stab in the dark guessing where these go I've not the competence to check.

I'm going to be checking these, but no guarantee.

Feedback appreciated, I'll fix docs ect when we establish whether there's a better way about this rather than UpdateStatusRaw

### CODE REVIEW

**Comment by SilverCory** [comment]
Those test structs don't work I'll revert those soon.

**Comment by iopred** [comment]
I would like to see the status updating from https://github.com/bwmarrin/discordgo/pull/459 added to this PR.

I would prefer we create a `UpdateStatusComplex(data UpdateStatusData)` so that we future proof the API for next time too :)

**Comment by SilverCory** [comment]
I agree with that, do you want me to merge #459 to this then?

**Comment by iopred** [comment]
So I'd like to change UpdateStatusRaw in this PR to:

`UpdateStatusComplex(data UpdateStatusData)`

Exporting updateStatusData seems like it's more future proof.

**Comment by SilverCory** [comment]
Yeah I can see that being the case. I'll do this within an 2 hours if that's okay

**Comment by iopred** [comment]
No rush, please take your time!

**Comment by iopred** [comment]
Could you make this change into the `develop` branch too? We don't PR into master.

**Comment by SilverCory** [comment]
Would you like UpdateStatus and UpdatingStremingStatus to fall back to UpdateStatusComplex, aswell then? and yeah sure.

**Comment by iopred** [comment]
Yeah they should just call into UpdateStatusComplex.

**Comment by SilverCory** [comment]
#462

**Pull request closed without merging**
