### PR TITLE
Fix unmarshall error with Invite, improve error logging.

### PR DESCRIPTION
**Pull request by iopred**
Who gets paid for this again?

### CODE REVIEW

**Comment by b1naryth1ef** [comment]
@iopred not you with those CI failures. Disappoint.

**Comment by iopred** [comment]
Actually I have no idea what those failures are, it's in files not in this PR :|

**Comment by bwmarrin** [comment]
Way to go, breaking code you didn't even touch.  This is why we can't have dev as our default branch.

**Comment by bwmarrin** [comment]
Haha...  Rekt by github...

'''Pull requests that have a failing status can’t be merged from a phone.'''

**Pull request merged**
