### PR TITLE
Variadic option to AddHandler() function

### PR DESCRIPTION
**Pull request by umarquez**
Could be usefull to have a variadic method for this action, it is an idiomatic way to manage a multiple adds in a single step.

### CODE REVIEW

**Comment by bwmarrin** [comment]
I'm on the fence about this - so I'm going to leave this up for a bit longer.  If you (whoever is reading this) feel adding this to the library would be a benefit please add a comment here to let me know and ideally give an example of the benefit.   

Otherwise, I am trying to envision how using this would look and it seems messy to me. I'd hate to add functions to the library that might encourage messy code.

**Comment by qaisjp** [comment]
I am apathetic about this feature, but it would simplify this:

```go
	discord.AddHandler(discord.OnReady)
	discord.AddHandler(discord.onMessageCreate)
	discord.AddHandler(func(s *discordgo.Session, m *discordgo.WebhooksUpdate) {
		fmt.Printf("%+x\n", *m)
	})

	if !bridge.Config.SimpleMode {
		discord.AddHandler(discord.onMemberListChunk)
		discord.AddHandler(discord.onMemberUpdate)
		discord.AddHandler(discord.onPresencesReplace)
		discord.AddHandler(discord.onPresenceUpdate)
	}
```

to

```go
	discord.AddHandlers(discord.onReady, discord.onMessageCreate)

	if !bridge.Config.SimpleMode {
		discord.AddHandlers(discord.onMemberListChunk, discord.onMemberUpdate, discord.onPresencesReplace, discord.onPresenceUpdate)
	}
```

**Comment by neuronpool** [comment]
I think a change like this would improve overall readability, and would not increase complexity under the hood very much.

**Comment by umarquez** [comment]
> @umarquez how do you feel about making this change to AddHandler instead, since it won't break the API and it keeps us from having two nearly identical functions.

Looks like it is the optimal way to implement it, I'm agree with it.

**Comment by bwmarrin** [comment]
Great, then if you want to update this PR, or close and reissue a new one, then we'll get it merged.

**Comment by CarsonHoffman** [comment]
Given that the target branch is incorrect here (it should be `develop`, not `master`), I'm going to close this, as even with an update it'd be impossible to merge. If you'd still like this functionality, feel free to open a new PR with the requested changes against the `develop` branch!

**Pull request closed without merging**
