### PR TITLE
Add GuildID to Message

### PR DESCRIPTION
**Pull request by lloti**
The Discord API now provides a `guild_id` property so you don't have to get the channel first.

Edit: realized that a couple more events provide the `guild_id`, I'll be adding them in a moment

### CODE REVIEW

**Comment by Seklfreak** [comment]
Looks like the `guild_id` field is included in all events from Guilds now:
https://github.com/discordapp/discord-api-docs/issues/582

 I think the field could also be useful at the `MessageReaction` struct.

**Comment by iopred** [comment]
This is already merged in the `develop` branch.

**Comment by iopred** [comment]
Oops, my bad, I was confusing it with `Channel` struct, please make this PR into the `develop` branch. Thanks!

**Comment by lloti** [comment]
I'll re-open a complete pull request in a bit, just going to close this for now.

**Pull request closed without merging**
