### PR TITLE
update Activity struct and add emoji functions

### PR DESCRIPTION
**Pull request by post04**
I added a function to easily get the emojis out of a message and updated the Activity struct to include everything from the documentation.

### CODE REVIEW

**Comment by CarsonHoffman** [comment]
I'm a bit confused about the use of inline struct definitions here—we have struct definitions in the library for the [`Timestamps`](https://pkg.go.dev/github.com/bwmarrin/discordgo#TimeStamps), [`Emoji`](https://pkg.go.dev/github.com/bwmarrin/discordgo#Emoji), and [`Assets`](https://pkg.go.dev/github.com/bwmarrin/discordgo#Assets) fields, and the remaining two fields should be fairly easy to extract into named types. Using inline struct definitions makes the types extremely difficult to work with (specifying a literal of the type requires repeating the entire struct definition, rather than the name of a type).

In addition, given that `CreatedAt` represents a time, it seems to me that it should really be of type `time.Time`. Not all types in the library currently exhibit this behavior, but implementing a custom `UnmarshalJSON` is pretty trivial (especially once it is a named type!), and saves the user from having to perform this conversion themself.

**Comment by post04** [comment]
> I'm a bit confused about the use of inline struct definitions here—we have struct definitions in the library for the [`Timestamps`](https://pkg.go.dev/github.com/bwmarrin/discordgo#TimeStamps), [`Emoji`](https://pkg.go.dev/github.com/bwmarrin/discordgo#Emoji), and [`Assets`](https://pkg.go.dev/github.com/bwmarrin/discordgo#Assets) fields, and the remaining two fields should be fairly easy to extract into named types. Using inline struct definitions makes the types extremely difficult to work with (specifying a literal of the type requires repeating the entire struct definition, rather than the name of a type).
> 
> In addition, given that `CreatedAt` represents a time, it seems to me that it should really be of type `time.Time`. Not all types in the library currently exhibit this behavior, but implementing a custom `UnmarshalJSON` is pretty trivial (especially once it is a named type!), and saves the user from having to perform this conversion themself.

Thanks for the response! I completely understand what you're saying about the inline type definitions. The only thing I'm not understanding is CreatedAt being a time.Time, I've tried to do this and it seems to return an error unmarshaling. With that being said I've made all the other edits!

**Comment by hhhapz** [comment]
Please correct me if I'm incorrect, but it doesn't seem like your current implementation supports extracting unicode emojis either. Is that intentional?

**Comment by post04** [comment]
> Please correct me if I'm incorrect, but it doesn't seem like your current implementation supports extracting unicode emojis either. Is that intentional?

You'd be correct, that's intentional as I'm not sure how I'd be able to do that. I could pull the list from discord but besides adding that big chunk of data I'm unsure how I'd go about doing that. Perhaps I should rename the func to `GetCustomEmojis`?

**Comment by CarsonHoffman** [comment]
Thank you for the changes! Having that timestamp parsing done in the unmarshaling step makes the `CreatedAt` field much simpler to interact with 🤠

**Pull request merged**
