### PR TITLE
feat(GuildAuditLogEntryCreate): add guild_id

### PR DESCRIPTION
**Pull request by rwhelan**
Adds the field GuildID to the AuditLogEntry struct.  While not documented (https://discord.com/developers/docs/resources/audit-log#audit-log-entry-object-audit-log-entry-structure) it is part of the struct sent on the wire: 
image

### CODE REVIEW

**Comment by AbduAmeen** [comment]
I rely on this change so if we can get it merged soon, that would be great. Thanks

**Comment by rwhelan** [comment]
bump?  This should be an easy merge

**Comment by rwhelan** [comment]
image

**Comment by FedorLap2006** [comment]
Sorry for leaving this without an answer for quite some time.
We usually don't merge stuff if it's not in the API documentation.
Thus a PR to https://github.com/discord/discord-api-docs documenting this field has to be made first.

P.S. I can probably get around it today, however it'll take quite a while to get merged.

**Comment by hhaste** [comment]
> Sorry for leaving this without an answer for this much time. We usually don't merge stuff if it's not in the API documentation.
> 
> There's currently an open [PR](https://github.com/discord/discord-api-docs/pull/6228/) for this, so moving forward with this PR will be only possible after that one is merged.
> 
> P.S. It should be noted there's also [discord/discord-api-docs#5865](https://github.com/discord/discord-api-docs/pull/5865), however it was closed a while ago.

Does it really matter that much if it's "undocumented"? Seems like a no-brainer to approve this merge. I really doubt this field would be omitted in a future update - it's not like audit logs are a thing outside of guilds lol. 

This event is pretty much useless if we don't know which guild the event is dispatched from. Kindly reconsider.

**Comment by rwhelan** [comment]
> > Sorry for leaving this without an answer for this much time. We usually don't merge stuff if it's not in the API documentation.
> > There's currently an open [PR](https://github.com/discord/discord-api-docs/pull/6228/) for this, so moving forward with this PR will be only possible after that one is merged.
> > P.S. It should be noted there's also [discord/discord-api-docs#5865](https://github.com/discord/discord-api-docs/pull/5865), however it was closed a while ago.
> 
> Does it really matter that much if it's "undocumented"? Seems like a no-brainer to approve this merge. I really doubt this field would be omitted in a future update - it's not like audit logs are a thing outside of guilds lol.
> 
> This event is pretty much useless if we don't know which guild the event is dispatched from. Kindly reconsider.

image

**Comment by hhaste** [comment]
@FedorLap2006 Several other libs support this feature, so there is virtually no reason not to merge this 🤔

JDA: https://docs.jda.wiki/net/dv8tion/jda/api/events/guild/GenericGuildEvent.html#getGuild()
Discord.JS: https://github.com/discordjs/discord.js/blob/main/packages/discord.js/src/client/actions/GuildAuditLogEntryCreate.js#L10
Discord.NET: https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.WebSocket/Entities/AuditLogs/SocketAuditLogEntry.cs/#L22
Discord.PY: https://github.com/Rapptz/discord.py/blob/0e016be42ca4f34bb89761261a1c7c12f4cc8c48/discord/types/gateway.py#L351

**Comment by hhaste** [comment]
Also @rwhelan - it is more appropriate to implement this field on the `GuildAuditLogEntryCreate` struct (events.go:406) rather than `AuditLogEntry`, since guild ID is only ever included from this particular gateway payload.

**Comment by Earlopain** [comment]
The discord api docs PR for this field is now merged

**Comment by FedorLap2006** [comment]
Thank you for the contribution

**Pull request merged**
