### PR TITLE
Prevent login crash by assuming a json.Unmarshal "just works"

### LINKED ISSUE #46: Calls to Login func with invalid email/password crash.
Login func should return an error instead of crashing the entire application when called with an invalid username or password :)

### PR DESCRIPTION
**Pull request by sethdmoore**
Tested (with $ iptables -A INPUT -s 104.16.59.5 -j DROP )
It works.
Fixes #46

### CODE REVIEW

**Comment by sethdmoore** [comment]
This could (and should) be merged into Master as well. I'm working off my fork.

**Comment by bwmarrin** [comment]
Thanks for the PR @sethdmoore I definitely appreciate it.

**Comment by sethdmoore** [comment]
No problem @bwmarrin, it's a great library :)
:+1:

**Comment by bwmarrin** [comment]
Thanks :)

**Pull request merged**
