### PR TITLE
Private locks on most structs with locks

### PR DESCRIPTION
**Pull request by BigHeadGeorge**
#401 
State still has a public lock for iterating over stuff like guilds and channels because something like putting a lock on Ready seems unnecessary

### CODE REVIEW

**Comment by bwmarrin** [comment]
While I think moving the mutex locks to private is a good idea - this PR includes some other non-related changes.  Do you think you could clean up the PR to include only changes related to the mutex locks?

**Comment by BigHeadGeorge** [comment]
Yup, lemme clean it up real quick

**Comment by BigHeadGeorge** [comment]
I think that's the only unrelated thing, but without it accessing VoiceConnections won't be safe because of private locks. Maybe that's an issue for another PR though idk

**Comment by bwmarrin** [comment]
@gogitops can you please remove all of your reviews from this repository, they're essentially spam.  Unfortunately github doesn't seem to provide me a way of doing it otherwise I would delete them all.

**Comment by gogitops** [comment]
@bwmarrin deleted comments on all PRs in this org. Bot went a bit wild by accident. Fix has been implemented. Won't happen again.

**Comment by bwmarrin** [comment]
Thank you @gogitops  :) Much appreciated.

**Pull request closed without merging**
