### PR TITLE
Add support for news channels

### LINKED ISSUE #799: Add Support for /followers and /crosspost endpoints
As per https://github.com/discord/discord-api-docs/issues/1510, the `/followers` and `/crosspost` endpoints for news channels (now available to all servers, rather than just Verified/Partnered/Dev) is allowed to be accessed by bots. These endpoints are yet to be documented but the issue is labeled "documentation-needed" and there is an open PR for it as well, https://github.com/discord/discord-api-docs/pull/1692.

With that, it would be cool to see support for these endpoints within Discordgo, I would love to add these features myself, but want to open it for conversation beforehand.

Thoughts? Thanks in advance!

### PR DESCRIPTION
**Pull request by adityaxdiwakar**
Resolves #799 

Adds support for the following endpoints:
- `@/channels/:id/messages/:id/crosspost`: publishes a message in a news channel to followers
- `@/channels/:id/followers`: follows a news channel

### CODE REVIEW

**Comment by CarsonHoffman** [comment]
It doesn't appear that there's any way to extract the webhook ID from the `ChannelNewsFollow` method if I'm understanding the docs PR correctly; we'd definitely want to support getting back any available information on any new requests we add.

**Comment by adityaxdiwakar** [comment]
My bad, I've implemented that now in eb70c17733f3795f1cc40cd9b8db6c774deb20c0.

**Comment by CarsonHoffman** [comment]
It also seems that the error on `s.RequestWithBucketID` in `ChannelNewsFollow` isn't checked; this leads to `nil` errors being incorrectly being returned by the function as long as the body is empty or valid JSON, so errors like 401, 403 or 404 result in `nil` errors.

**Comment by adityaxdiwakar** [comment]
Not sure how I missed that, thanks, resolved!

**Comment by CarsonHoffman** [comment]
Awesome, the methods look great now. Thank you for the PR!

**Pull request merged**
