### PR TITLE
Add banner to GuildParams struct

### PR DESCRIPTION
**Pull request by samuel-hunter**
I've tested this on a server with Banner permissions, and it works as perfect as I can tell.

### CODE REVIEW

**Comment by samuel-hunter** [comment]
I've made my own fork of this library with the change added so I can continue developing on my discord bot, and the operation has been working flawlessly for the past 3 weeks!

**Comment by samuel-hunter** [comment]
Right, I missed that. It looks like the `develop` branch already has the needed change!

**Comment by samuel-hunter** [comment]
Hi,
Checking back on this a few months later I noticed that the `develop` branch is missing, the feature doesn't look like it's added _yet_, and the Contributing guidelines points to the `master` branch, so I think this pull request is worth another look at!

I've rebased my fork and got no merge conflicts. It looks like everything should be OK!

**Comment by CarsonHoffman** [comment]
LGTM; thanks for the PR! I'm sorry for the confusion—when ewohltman made their comment they were correct, but in the meantime we consolidated the codebase into a single branch to make things easier for contributors. We did perform a final merge of `develop` into `master` before making that change, however, so if it isn't there now I'm not sure it was actually ever present in `develop`. Either way, thanks!

**Pull request merged**
