### PR TITLE
Fixed typo "consistancy" to "consistency"

### PR DESCRIPTION
**Pull request by RoJamieson**
📝 Changed "consistancy" in msglog comment in logging.go to "consistency".

### CODE REVIEW

**Comment by RoJamieson** [comment]
I realise I did the pull request to bwmarrin:master instead of develop. This is my first contribution in github, is there anyway I can change it?

**Comment by CarsonHoffman** [comment]
Unfortunately, this PR is now based on the `HEAD` of `master`, rather than of `develop`; just changing the target branch won't fix that. You could try rebasing your fork branch onto the `HEAD` of `develop`, or open a new PR after creating a commit based on the `develop` branch.

**Comment by RoJamieson** [comment]
Ok thank you. I'll try to give that a go.

**Comment by RoJamieson** [comment]
I've now made a new pull request with the same changes. Hope it works.

**Pull request closed without merging**
