### PR TITLE
Add context.Context parameter to all REST API functions

### PR DESCRIPTION
**Pull request by jalavosus**
Go's `context.Context` builtin is extremely common when performing HTTP requests of any kind. Currently, discordgo does not allow API consumers to pass a Context, which means that operations which might time out -- or should -- are more or less left in the void. 

In one project I work on, this has forced me to use the following workaround: 

```go
SendMessage(ctx context.Context, session *discordgo.Session, msg string, channelId string) error {
    ch := make(chan error)
    
    ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
    defer cancel()

    go func(ctx context.Context, session *discordgo.Session, msg string, ch chan<- error) {
        _, sendErr := session.ChannelMessageSend(channelId, msg)
        if sendErr != nil {
            ch <- errors.Wrapf(sendErr, "error sending message to channel ID %[1]s", channelId)
            return
        }

        ch <- nil
    }(ctx, session, msg, ch)

    for {
        select {
        case <-ctx.Done():
            return ctx.Err()
        case sendMsgErr := <-ch:
            return sendMsgErr
        }
    }
}
```

Even that isn't a great workaround, since whether or not the message actually ends up being sent is unknown - I just know that my context timed out. It could fail, which in the case of a context timeout is optimal, or it could send; in the case of a context timeout, functions which check for errors might queue up messages for a retry if they "fail", which would mean multiple sends. Multiple sends is anywhere from annoying to production blocking. 

Using a user-supplied `context.Context` for all REST API interactions therefore allows for idempotent interactions with the API, which can be extremely important depending on the use case. 

Issue reference: #752

### CODE REVIEW

**Comment by FedorLap2006** [comment]
Hi. Thank you for the Pull Request. The only problem is that it would break a lot of existing code.
I'll give it a look nonetheless

**Comment by FedorLap2006** [comment]
This PR would break 90% of the already existing code, so I'm not sure about merging it.
Additionally, note the checks.

**Comment by jalavosus** [comment]
> While it would be good to have this in the long run, it would just break too much stuff.

I don't disagree, but I'm also not advocating this to be featured in a point release; that is to say, such a change would and should only be part of a major version release.

> P. S. Note the checks

I'll fix the formatting check when I'm able to, though I do appreciate the heads up on it

**Comment by jalavosus** [comment]
@FedorLap2006 I do appreciate that you didn't immediately close the issue 😊 as a developer who uses this library in production, I very much understand -- and support -- the need to not introduce breaking changes in the short term. Heck, I'd be pissed if someone else introduced this change and wanted it in the next minor version release. 

That being said, the use case for user -supplied `context.Context` params is there and likely widely useful to more developers/API consumers than just myself. Even if not in the next major release, even one after it would.be far more valuable than letting the concept languish. 

Either way, thanks a bunch truly 🌈

**Comment by caibirdme** [comment]
Hope this pr could be merged! We really need the context.Context to propagate tracing information and control the timeout

**Comment by FedorLap2006** [comment]
Hi everyone!

In the latest release (v0.27), we've introduced the options, which included `discordgo.WithContext`. The option which achieves the same functionality as this PR outlined. Due to this, I would have to close this PR.

Thanks for patience from everyone who participated and waited for this. And thanks to @jalavosus for pointing out the issue in the first place.

**Pull request closed without merging**
