### PR TITLE
Implement new status types

### PR DESCRIPTION
**Pull request by PixeLInc**
Implement the new Listening & Watching status types.
Also, moved UpdateStreamStatus to a new method to accept the new GameType parameter and made the old method use the new method.

### CODE REVIEW

**Comment by iopred** [comment]
Don't you just want UpdateStatusComplex?

**Comment by PixeLInc** [comment]
Well, sure you could use that but I felt like it would be easier to just use the defined method for it just like the UpdateStatus/UpdateStreamingStatus method where it explicitly sets it so you don't have to know the type number or anything of that sort, no?

**Comment by iopred** [comment]
The problem with adding new methods is that the discord API is always changing, the thing we try to do the least is break current users of the API. The complex method's tend to be a little bit more resilient to API changes in the future, which is why we tend to prefer them.

**Comment by PixeLInc** [comment]
Okay. Well then I'll just close up this PR.

**Pull request closed without merging**
