### PR TITLE
Added more fields

### PR DESCRIPTION
**Pull request by LEGOlord208**

### CODE REVIEW

**Comment by iopred** [comment]
We probably want these to be pointers like VerificationLevel, so we can determine which things to send to Discord.

Also omitempty wont do anything unless they are pointers... finally, this struct doesn't go over the network so it doesn't need any JSON tags.

**Comment by LEGOlord208** [comment]
Pretty sure omitempty on a string makes it omit if empty. e.g. `== ""`

**Comment by iopred** [comment]
https://play.golang.org/p/YFv6JMZsqZ

Sadly no :(

**Comment by LEGOlord208** [comment]
That only affects pointers. If the string is not a pointer, it will omit empty.

**Comment by iopred** [comment]
:100: 

Well my other comment still stands, the GuildParams struct doesn't need JSON attributes, unless you're planning on changing GuildEdit to just pass the struct along instead of copying all the fields.

**Comment by LEGOlord208** [comment]
Ohhh it doesn't do that!  
Didn't realize, sorry

**Pull request merged**
