### PR TITLE
Emoji improvements

### PR DESCRIPTION
**Pull request by robbiet480**
- Re-arrange Emoji to match docs
- Add new function `GuildEmoji` to get all the emoji part of a guild. The style of other GET functions is to pluralize the resource type, but pretty sure Emoji is used as both singular and plural form. Happy to change it to be `GuildEmojis` though.

### CODE REVIEW

**Comment by CarsonHoffman** [comment]
Hi, thanks for the PR! We actually had a PR come in right before yours that added the `User` field, however your other changes still seem worthwhile! I would vote for using `Emojis` as the terminology; although this might be dubious from a language perspective it would help to keep it in line with other usages in the library, making it clear that it's talking about the plural. If you're able to rebase your PR onto the up-to-date version of `develop` and take out the addition of the `User` field, as well as move to `Emojis`, LGTM!

**Comment by robbiet480** [comment]
Sure thing, just give me a few minutes and I'll get it done!

**Comment by robbiet480** [comment]
@CarsonHoffman All done and ready for merge.

**Comment by CarsonHoffman** [comment]
Great, thanks for the quick update and for the PR as a whole!

**Pull request merged**
