### PR TITLE
chore: add missing fields in User struct

### PR DESCRIPTION
**Pull request by moul**
based on https://discord.com/developers/docs/resources/user

### CODE REVIEW

**Comment by moul** [comment]
:wave: sorry I didn't see that my PR was red on CI, I just fixed everything and force-pushed :)

**Comment by CarsonHoffman** [comment]
Sorry for the wait—with a change like this the biggest concern is the usability of the interface. It would be great to have an indication in the comments of `PremiumType` and `Flags` that these fields are only available when the request is authorized via a Bearer token, otherwise LGTM!

**Comment by adityaxdiwakar** [comment]
If this is still being worked on or is being updated (cc @moul), #801 has been merged adding some changes to `users.go`, some of which overlapped with the proposed changes from this PR as well, so this would need to be updated, just as an FYI.

**Comment by moul** [comment]
@CarsonHoffman thanks, comments added
@adityaxdiwakar thanks, rebased

**Comment by CarsonHoffman** [comment]
Sorry for missing the update on this. Thank you for the additions!

**Pull request merged**
