### PR TITLE
Components Support

### PR DESCRIPTION
**Pull request by fletcherist**
Spec: https://discord.com/developers/docs/interactions/message-components

### CODE REVIEW

**Comment by Pedro-Pessoa** [comment]
Isn't this already being worked on #933?

**Comment by FedorLap2006** [comment]
Same question.

**Comment by fletcherist** [comment]
@Pedro-Pessoa not exactly. The implementation by @FedorLap2006 breaks backwards-compatibility and contains breaking changes. This, on the other hand, can be released as minor patch.
Screen Shot 2021-06-23 at 1 19 26 PM

So i think the best way is to treat this as yet another approach

**Comment by CarsonHoffman** [comment]
The changes introduced in the existing PR serve to more closely align the library with the state of the world on Discord's end after _they_ made some breaking changes; it's not worth having incorrectly-named things years down the line in the name of backwards compatibility on a feature that **has yet to appear in any tagged release** (i.e. it's not really a breaking change at all).

I don't mean to shoot you down too hard, but at this point, I see no reason that the other PR cannot be moved ahead with, so if you'd like to see buttons in the library as soon as possible, I'd suggest contributing a bit of your time as a review on that PR rather than duplicating effort.

**Comment by fletcherist** [comment]
@CarsonHoffman okay I clearly got your idea. Closing this tho, thanks for explanation

**Pull request closed without merging**
